name: FMD Tool CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    name: Build, Lint, and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Lint Python code with flake8
        run: |
          echo "Running Python linter..."
          flake8 fmd_tool/ --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 fmd_tool/ --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics

      - name: Run Python unit tests with pytest
        run: |
          echo "Running unit tests..."
          pytest tests/ --disable-warnings --maxfail=3

  lint-markdown:
    name: Lint and Auto-Fix Markdown Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install markdownlint-cli2 globally
        run: npm install -g markdownlint-cli2

      - name: Auto-fix markdownlint issues
        run: markdownlint --fix documentation/**/*.md

      - name: Commit fixed markdown files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add documentation/**/*.md
          git diff --cached --quiet || git commit -m "chore: auto-fix markdownlint issues"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
